version: 0.1

phases:
  build:
    commands:
      - echo Nohing to do yet
artifacts:
  files:
    - about.html
    - assets/*
    - gigs.html
    - .gitignore
    - images/*
    - index.html
    - instagram.html
    - README.md
    - releases.html
    - styles/*
    - buildspec.yml
    - dynamic-lamba.py
