version: 0.1

phases:
  build:
    commands:
      - echo Nohing to do yet
artifacts:
  files:
    about.html
    assets/css/*
    assets/fonts/*
    assets/js/*
    gigs.html
    images/*
    index.html
    instagram.html
    README.md
    releases.html
    styles/*
